# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:34"
      timezone: "Asia/Tokyo"
    assignees:
      - "Ningensei848"
    target-branch: "main"
    versioning-strategy: "lockfile-only"
    commit-message:
      # Prefix all commit messages with "npm: ~"
      prefix: "[npm]"
    # Specify labels for npm pull requests
    labels:
      - "help wanted"
      - "dependencies"
    open-pull-requests-limit: 2

  # for `src/libs/tweetBot` ---------------------------------------------------
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/libs/tweetBot" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:34"
      timezone: "Asia/Tokyo"
    assignees:
      - "Ningensei848"
    target-branch: "main"
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "[npm]"
    labels:
      - "help wanted"
      - "dependencies"
    open-pull-requests-limit: 2
