# テンプレートの仕組みと書き方
# cf. https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
# cf. https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: 🐛 バグを報告する
description: '[Get started] を選択して送信フォームを作成してください'
title: '[Bug]: '
labels: ['bug']
assignees:
    - Ningensei848
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: what-happened
      attributes:
          label: 直面している問題について
          description: できるだけ具体的な状況を記述してください
          placeholder: Tell us what you see!
          value: 'A bug happened!'
      validations:
          required: true
    - type: dropdown
      id: browsers
      attributes:
          label: ご利用のブラウザについて選択してください
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - Other
      validations:
          required: true
    - type: markdown
      attributes:
          value: 'バグ報告にご協力いただき感謝申し上げます!! 今後ともよろしくお願いいたします m(_ _)m'
