# テンプレートの仕組みと書き方
# cf. https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
# cf. https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: 🐛 Bug Report (for Users)
description: File a bug report for general users
title: '[Bug]: '
labels: ['bug', 'triage']
assignees:
    - Ningensei848
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: what-happened
      attributes:
          label: 直面している問題について
          description: できるだけ具体的な状況を記述してください
          placeholder: Tell us what you see!
          value: 'A bug happened!'
      validations:
          required: true
    - type: dropdown
      id: browsers
      attributes:
          label: ご利用のブラウザについて選択してください
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - Other
      validations:
          required: true
    # - type: textarea
    #   id: logs
    #   attributes:
    #       label: Relevant log output
    #       description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    #       render: Shell
    # - type: checkboxes
    #   id: terms
    #   attributes:
    #       label: Code of Conduct
    #       description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    #       options:
    #           - label: I agree to follow this project's Code of Conduct
    #             required: true
    - type: markdown
      attributes:
          value: 'バグ報告にご協力いただき感謝申し上げます!! 今後ともよろしくお願いいたします m(_ _)m'
