# テンプレートの仕組みと書き方
# cf. https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
# cf. https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

# 構造を参考にしたもの
# cf. https://github.com/eta-dev/eta/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

name: 🐛 Bug Report (for Developers)
description: File a bug report for developers
title: '[Bug]: '
labels: ['bug']
assignees:
    - Ningensei848
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: input
      id: os-version
      attributes:
          label: Operating System
          description: What operating system are you using?
          placeholder: 'ex. macOS Big Sur'
          value: operating system
      validations:
          required: true
    - type: dropdown
      id: nodejs-version
      attributes:
          label: Node.js Version
          description: What version of our `Node.js` are you running?
          multiple: false
          options:
              - '>= 18.16 (Default)'
              - '19.x'
              - '20.x'
      validations:
          required: true
    - type: markdown
      attributes:
          value: |
              Tips: If you do not know the version, run `node -v` to display it.
    - type: input
      id: npm-version
      attributes:
          label: NPM Version
          description: What version of our `npm` are you running?
          placeholder: ex. 9.7.1
      validations:
          required: true
    - type: markdown
      attributes:
          value: |
              Tips: If you do not know the version, run `npm -v` to display it.
    - type: textarea
      id: describe
      attributes:
          label: Step 1. Describe the bug
          description: Tell us what problems you faced?
          placeholder: A clear and concise description of what the bug is.
      validations:
          required: true
    - type: textarea
      id: reproduce
      attributes:
          label: Step 2. To Reproduce
          description: Describe exactly the procedures to be followed to reproduce it.
          placeholder: Steps to reproduce the behavior
          value: |
              1. Type in '...'
              2. Call function '...'
              3. Look at result in '...'
      validations:
          required: true
    - type: textarea
      id: expected-behavior
      attributes:
          label: Step 3. Expected behavior
          description: What did you expect to happen?
          placeholder: A clear and concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      id: screenshot
      attributes:
          label: Step 4. Screenshots (Optional)
          description: If applicable, add screenshots to help explain your problem.
          placeholder: |
              Tips: Drag and drop, or if you are using a PC, copy and paste an image file, and the image will be uploaded.
      validations:
          required: false
    - type: textarea
      id: additional-context
      attributes:
          label: Step 5. Additional context (Optional)
          description: Add any other context about the problem here.
      validations:
          required: false
    - type: markdown
      attributes:
          value: 'Thanks for completing our form!'
