blank_issues_enabled: false
contact_links:
    - name: A-gebahyo Twitter DM
      url: https://twitter.com/messages/compose?recipient_id=1509799284388265987
      about: Contact Support if you're having trouble with your contribution.
