# テンプレートの仕組みと書き方
# cf. https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
# cf. https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

# 構造を参考にしたもの
# cf. https://github.com/eta-dev/eta/blob/main/.github/ISSUE_TEMPLATE/feature_request.md

name: 🚀 Feature request
description: File suggest an idea for this project
title: '[Feature]: '
labels: ['feature', 'triage']
assignees:
    - Ningensei848
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this feature request!
    - type: textarea
      id: describe
      attributes:
          label: Step 1. Describe the related problem
          description: A clear and concise description of what the problem is.
          placeholder: ex. I'm always frustrated when [...]
      validations:
          required: true
    - type: textarea
      id: solution
      attributes:
          label: Step 2. Describe the solution you'd like
          description: A clear and concise description of what you want to happen.
          placeholder: please describe what you want to happen
      validations:
          required: true
    - type: textarea
      id: solution-alt
      attributes:
          label: Step 3. Describe alternatives you've considered (Optional)
          description: A clear and concise description of any alternative solutions or features you've considered.
      validations:
          required: false
    - type: textarea
      id: additional-context
      attributes:
          label: Step 4. Additional context (Optional)
          description: Add any other context or screenshots about the feature request here.
      validations:
          required: false
    - type: markdown
      attributes:
          value: 'Thanks for completing our form!'
