name: Automatic Generation of Articles for Each Race

on:
    workflow_dispatch:
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron: '11 11 * * *'
    push:
        branches:
            - main
        # Review gh actions docs if you want to further define triggers, paths, etc
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
    deploy:
        name: Generate Articles
        runs-on: ubuntu-latest
        timeout-minutes: 10
        env:
            # secrets context
            # cf. https://docs.github.com/ja/actions/learn-github-actions/contexts#secrets-context
            ENDPOINT: ${{ secrets.ENDPOINT }}
            API_KEY: ${{ secrets.API_KEY }}
            ANOTHER_REPO: ${{ secrets.ANOTHER_REPO }}
            APP_ID: ${{ secrets.APP_ID }}
            APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

            # The following lines assign commit authorship to the official
            # GH-Actions bot for deploys to `gh-pages` branch:
            # https://github.com/actions/checkout/issues/13#issuecomment-724415212
            # The GH actions bot is used by default if you didn't specify the two fields.
            # You can swap them out with your own user credentials.
            BOT_USERNAME: github-actions[bot]
            BOT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

        steps:
            - uses: actions/checkout@v3

            - name: Generate Token from My GitHub Apps
              id: generate_token
              # cf. https://github.com/marketplace/actions/action-github-app-token
              uses: getsentry/action-github-app-token@v2
              with:
                  app_id: ${{ env.APP_ID }}
                  private_key: ${{ env.APP_PRIVATE_KEY }}

            - name: Checkout Another Repo
              uses: actions/checkout@v3
              with:
                  repository: ${{ env.ANOTHER_REPO }}
                  # `GH_PAT` is a secret that contains your PAT
                  # cf. https://github.com/actions/checkout#Checkout-multiple-repos-private
                  token: ${{ steps.generate_token.outputs.token }}
                  sparse-checkout: .gitignore
                  sparse-checkout-cone-mode: false
                  path: content/docs

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm

            - name: Install Dependencies from Lockfile
              run: npm ci

            - name: Generate Articles
              run: npm run eta:prod
              env:
                  API_KEY: ${{ env.API_KEY }}
                  ENDPOINT: ${{ env.ENDPOINT }}

            - name: Push to Another Repo
              working-directory: ./content/docs # prefix `./` is essential
              run: |
                  git sparse-checkout disable
                  git config --local user.name ${{ env.BOT_USERNAME }}
                  git config --local user.email ${{ env.BOT_EMAIL }}
                  git config --list
                  git status
                  git add .
                  git commit -m "[GitHub Actions BOT] Articles updated || $(date)"
                  git push
